# Generated by Django 4.2.9 on 2024-04-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menu_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_category',
            options={'ordering': ('category',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='menu',
            name='Option',
            field=models.CharField(default='default_option', max_length=20, verbose_name='OPTION'),
        ),
        
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=20, verbose_name='MENU NAME'),
        ),
        migrations.DeleteModel(
            name='Menu_Option',
        ),
    ]
