# Generated by Django 4.2.9 on 2024-04-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_menu_category_options_menu_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_dt', models.DateTimeField(auto_now_add=True)),
                ('wait_id', models.IntegerField()),
                ('menu_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_order_set', to='cafe.shopping_cart')),
                ('menu_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_quantity_set', to='cafe.shopping_cart')),
            ],
        ),
        migrations.AddField(
            model_name='menu_category',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='cafe.order'),
        ),
    ]
