# Generated by Django 4.2.9 on 2024-04-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_order_menu_category_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='price',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menu_price_items', to='cafe.menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='total_amount',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='total_price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='menu_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_name_items', to='cafe.menu'),
        ),
    ]
