# Generated by Django 4.2.9 on 2024-04-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_alter_order_menu_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Option',
            new_name='option',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_option', to='cafe.menu'),
        ),
    ]
